
# Estudo de Caso - Compras de Ecommerce  

Neste exmplo, iremos explorar e analizar alguns dados falsos sobre algumas compras feitas pela Amazon!
____
**Importe pandas e leia o arquivo csv "Ecommerce Purchases" e configure-o para um DataFrame chamado ecom.**

In [1]:
import pandas as pd

In [2]:
# Para ler um arquivo csv usamos o método pd.read_csv()
ecom = pd.read_csv("Ecommerce Purchases.csv")

**Verifique o "head" do DataFrame.**

In [3]:
ecom.head(10) # .head() mostra as 5 primeiro linhas por padrão, porém você pode definir uma quantidade dentro dos parênteses

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

**Quantas linhas e colunas existem?**

In [4]:
ecom.shape # Exibe uma tupla com as quantidades (linhas, colunas)

(10000, 14)

In [5]:
ecom.info() # Mostra todas as informações gerais do DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

**Qual é o preço de compra médio?**

In [6]:
ecom['Purchase Price'].mean() # Aplica o método .mean() na coluna 'Purchase Price'

np.float64(50.347302)

**Quais foram os preços de compra mais altos e mais baixos?**

In [7]:
# Valor máximo na coluna 'Purchase Price'
ecom['Purchase Price'].max()

np.float64(99.99)

In [8]:
# Valor mínimo na coluna 'Purchase Price'
ecom['Purchase Price'].min()

np.float64(0.0)

**Quantas pessoas têm Inglês 'en' como sua língua de escolha no site?**

In [9]:
sum(ecom['Language'] == 'en') # ecom['Language'] == 'en' gera uma lista de True/False. 
# True equivale à 1 e False equivale à 0, portanto podemos somar os valores 'True' desta coluna

1098

In [10]:
ecom['Language'].value_counts() # Outra maneira de resolver seria verificando a contagem de cada idioma na coluna Language

Language
de    1155
ru    1155
el    1137
pt    1118
en    1098
fr    1097
es    1095
it    1086
zh    1059
Name: count, dtype: int64

**Quantas pessoas têm o cargo de "Advogado"?**

In [11]:
sum(ecom['Job'] == 'Lawyer')

30

**Quantas pessoas fizeram a compra durante a AM e quantas pessoas fizeram a compra durante o PM?**

In [ ]:
# Exemplo usando agrupamento com a função groupby()
ecom.groupby('AM or PM').count()

,Address,Lot,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
AM or PM,,,,,,,,,,,,,
AM,4932,4932,4932,4932,4932,4932,4932,4932,4932,4932,4932,4932,4932
PM,5068,5068,5068,5068,5068,5068,5068,5068,5068,5068,5068,5068,5068

In [12]:
ecom['AM or PM'].value_counts()

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

**Quais são os 5 títulos de trabalho mais comuns?**

In [13]:
# Neste caso, primeiro fazemos a contagem dos valores na coluna 'Job' e depois pegamos apenas os 5 primeiros.
ecom['Job'].value_counts().head() # .value_counts() já retorna a contagem ordenada do maior para o menor

Job
Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Research officer, political party    27
Designer, jewellery                  27
Name: count, dtype: int64

**Alguém fez uma compra que veio do Lot: "90 WT", qual foi o preço de compra para esta transação?**

In [14]:
# 1 - Primeiro fazemos a comparação ecom['Lot'] == '90 WT'. Isso retorna uma Series com True na(s) linha(s) onde 'Lot' é '90 WT' e False na restante
# 2 - Depois usamos essa Series como filtro, dentro do colchetes da própria variável ecom ecom[ecom['Lot'] == '90 WT'], 
# assim transformando ela de volta em um DataFrame filtrado
# 3 - Por último filtramos apenas a coluna 'Purchase Price' do DataFrame
ecom[ecom['Lot'] == '90 WT']['Purchase Price']

513    75.1
Name: Purchase Price, dtype: float64

**Qual é o email da pessoa com o seguinte número do cartão de crédito: 4926535242672853**

In [15]:
# Aqui podemos seguir a mesma lógica do exemplo anterior
ecom[ecom['Credit Card'] == 4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: object

**Quantas pessoas têm o American Express como seu fornecedor de cartão de crédito * e * fizeram uma compra acima de US $ 95?**

In [16]:
# Para combinar dois filtros utilizamos o símbolo '&' (que representa a mesma coisa que AND) no pandas

ecom[(ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95)].count()

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

**Difícil: quantas pessoas tem um cartão de crédito que expira em 2025?**

In [17]:
sum(ecom['CC Exp Date'].apply(lambda x: x[-2:] == '25'))

1033

A função apply() no Pandas é usada para aplicar uma função a cada elemento de uma coluna (ou linha) de um DataFrame ou Series. Já a função lambda é uma forma de criar funções anônimas, ou seja, funções rápidas e sem nome. No exemplo ecom['CC Exp Date'].apply(lambda x: x[-2:] == '25'), o apply() aplica a função lambda a cada valor da coluna 'CC Exp Date', verificando se os dois últimos caracteres (geralmente o ano de validade do cartão) são '25'. O sum() no início soma quantos desses valores retornaram True, ou seja, quantos cartões expiram em 2025.

**Difícil: quais são os 5 principais provedores de e-mail / hosts mais populares (por exemplo, gmail.com, yahoo.com, etc ...)**

In [18]:
ecom['Email'].apply(lambda x: x.split('@')[-1]).value_counts().head()

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

O código acima faz o seguinte:

- 1 - apply(lambda x: x.split('@')[-1]) → para cada e-mail na coluna 'Email', a função lambda separa o texto no caractere '@' e pega a parte depois dele (ou seja, o domínio do e-mail, como gmail.com, yahoo.com etc.).

- 2 - value_counts() → conta quantas vezes cada domínio aparece.

- 3 - head() → exibe apenas os 5 primeiros resultados (os provedores mais populares).